import sys, uuid
sys.path.insert(0, ".")
import h
PROMPTS = [
 "we just resumed after compaction, what is live now", "write the brief for the next lane and dispatch it",
 "run the contract gate on this increment", "the pc bridge sqlite query failed with no such column",
 "dispatch a hermes lane on the PC and size the local route", "why is the gitnexus index stale again",
 "do a premortem roast of the design", "bug echo after the fix, find similar bugs", "trace the chain from the hook to the model",
 "root cause the flaky test in test_session_hooks", "adversarial review of the S1-L1 hook", "ouroboros interview seed generation stalls",
 "vendor first: is there a library for this", "is the numeric guard fail-closed on NaN", "push the reviewed sha with push_clean",
 "the pytest count in the ledger is wrong", "thermo nuclear review of the release", "luck lens on the architecture decision",
 "empirical validation of the latency claim", "code intel quartet: graft ask who calls plan_tool",
 "commit this with safe_commit and push", "the anchor edit on the ledger failed", "podman image short name error on the PC",
 "the systemctl user unit restart on the PC failed with XDG_RUNTIME_DIR", "launch the pc lane with pc_lane.sh and re-attach it later",
 "session continuity: update the wiki live-state page", "deep work phase index for a new subsystem",
 "hollow green in the gate: mutation testing", "the retro gate fired, answer it", "research prompt for the dream phase",
 "thanks", "ok", "yes", "continue", "status?", "é" * 3000 + " contract gate", "contract " * 900,
 "<system-reminder> contract gate negotiate", "[Request interrupted by user] contract gate negotiate the contract",
 "Caveat: The messages below were generated by the user while running local commands. contract gate",
]
problems, stats = [], []
for p in PROMPTS:
    sid = "vs1p-" + uuid.uuid4().hex[:8]
    r = h.run(h.PROMPT, h.prompt(p, sid=sid))
    c = h.ctx(r)
    rec = h.telemetry()[-1]
    nb = len(c.encode()) if c else 0
    if nb > 4096 or rec.get("bytes") != nb:
        problems.append((PROMPTS.index(p), "bytes", nb, rec.get("bytes")))
    try:
        bl = h.check(c) if c else []
    except AssertionError as e:
        problems.append((PROMPTS.index(p), "oracle", str(e)[:160])); bl = []
    for b in bl:
        if b[0] != "prompt":
            problems.append((PROMPTS.index(p), "label", b[0]))
    per = [i.get("bytes", 0) for i in rec.get("injected", [])]
    if any(x > 2048 for x in per):
        problems.append((PROMPTS.index(p), "excerpt over 2048", per))
    skipped = [s["why"] for s in rec.get("skipped", [])]
    stats.append((PROMPTS.index(p), len(bl), nb, rec.get("why"), skipped, [x.rsplit(" (", 1)[0][:40] for x in rec.get("matched", [])[:2]], round(r.wall * 1000)))
    h.wipe_state()
for s in stats: print(s)
print("problems:", problems)
